### ISSUE TITLE
gitlab-ci-multi-runner register fails

### ISSUE THREAD

**Issue by edestecd** [frankiethekneeman/puppet-gitlab-ci-multi-runner#12]
It seems that --description is no longer a valid option

**Comment by edestecd** [comment]
Seems like the token is the only unique item, this should become the title...

**Comment by frankiethekneeman** [comment]
Token is not necessarily unique, as it's a registration token and not a runner token.

**Comment by edestecd** [comment]
Yes I realized that.  It was the description/name conversion that solved it for me.
