### ISSUE TITLE
On rhel/rpms systems gitlab-ci-multi-runner is excluded from yum/updates using yum.conf

### ISSUE THREAD

**Issue by gwarf** [frankiethekneeman/puppet-gitlab-ci-multi-runner#20]
Hi,
On rhel/rpms systems gitlab-ci-multi-runner is excluded from yum/updates using /etc/yum.conf.
See https://github.com/frankiethekneeman/puppet-gitlab-ci-multi-runner/blob/2.0/manifests/init.pp#L78 .
It prevents updating the package and even hides the fact that there are updates.
I am not sure why it would be desirable, but could this at least be an optional behaviour?

Thanks

**Comment by frankiethekneeman** [comment]
I prevent automagical updates because The maintainers of the gitlab-ci-runner introduce breaking changes quite frequently, as evidenced by how out of date this module already is.  I would accept an MR for optional behaviour.

**Comment by frankiethekneeman** [comment]
Oops.

**Comment by cablespaghetti** [comment]
I fixed this for rhel 7 in commit 75451ee6955a04d199ba0f13c1c8e417abf29a92 which is in the latest release.
