### ISSUE TITLE
After a package update the init script is no more working.

### ISSUE THREAD

**Issue by gwarf** [frankiethekneeman/puppet-gitlab-ci-multi-runner#21]
Hi,
After a package update the init script is no more working as the package's one is made for root and /etc/gitlab-runner/config.toml not for the dedicated gitlab_ci_multi_runner user and its specific config.toml.
The Exec['Ensure Service'] resource could have a check to test that the file is correct, or it might be simpler to use a File resource with a template.

Best

**Comment by frankiethekneeman** [comment]
I would accept an MR for this behaviour.
