### ISSUE TITLE
Config file being created in wrong place

### ISSUE THREAD

**Issue by sturdiva** [frankiethekneeman/puppet-gitlab-ci-multi-runner#22]
It appears that since ci-multi-runner 0.5.0 the config file needs to be created in `/etc/gitlab-runner/config.toml`, not `$HOME/.gitlab-runner/config.toml` (at least when running as root):

https://gitlab.com/gitlab-org/gitlab-ci-multi-runner#version-050

"Version 0.5.0 introduces many security related changes. One of such changes is the different location of config.toml. Previously (prior 0.5.0) config was read from current working directory. Currently, when gitlab-runner is executed by root or with sudo config is read from /etc/gitlab-runner/config.toml"

**Comment by frankiethekneeman** [comment]
#19 Fixes.  Look for a release shortly.
