### ISSUE TITLE
Runner Permission Denied

### ISSUE THREAD

**Issue by biggiemac** [frankiethekneeman/puppet-gitlab-ci-multi-runner#31]
I am seeing this error when attempting to apply my manifest file to install a ci multi runner:

PANIC: stat /home/gitlab_ci_multi_runner/.gitlab-runner/config.toml: permission denied
Error: gitlab-ci-multi-runner register --non-interactive --url=https://my_url --name=AUTOMATEDRUNNER --tag-list=AUTOMATED --registration-token=my_token  --executor=shell               returned 1 instead of one of [0]
Error: /Stage[main]/Main/Gitlab_ci_multi_runner::Runner[AUTOMATEDRUNNER]/Exec[Register-AUTOMATEDRUNNER]/returns: change from notrun to 0 failed: gitlab-ci-multi-runner register --non-interactive --url=https://my_url --name=AUTOMATEDRUNNER --tag-list=AUTOMATED --registration-token=my_token  --executor=shell               returned 1 instead of one of [0]

**Comment by cablespaghetti** [comment]
I've just had this. I can't work out what is creating the config file as root...
