### ISSUE TITLE
Allow to set a fixed version for package

### ISSUE THREAD

**Issue by EmteZogaf** [frankiethekneeman/puppet-gitlab-ci-multi-runner#34]
The version of the apt package is currently set to `latest`and can't be overridden [(init.pp)](https://github.com/frankiethekneeman/puppet-gitlab-ci-multi-runner/blob/master/manifests/init.pp#L70). Add a parameter to override the version to a user defined value.

**Comment by cablespaghetti** [comment]
I guess you had the same problem I had last night then? I'm working on this right now.

**Comment by EmteZogaf** [comment]
Yup, `status=401 Unauthorized` 😞 .

**Comment by cablespaghetti** [comment]
Check out the develop branch. It now has a $version parameter. I've set mine to present.

**Comment by EmteZogaf** [comment]
Thanks 👍

**Comment by cablespaghetti** [comment]
Fixed in fd650d7c1a933302dc0da748ffe10718bfa5e94d
